### ISSUE TITLE
Server full

### ISSUE THREAD

**Issue by Zen4** [ImagicalCorp/ImagicalMine#235]
It shows that the server is full although it is not.

**Comment by keithkfng** [comment]
Check your slots and everything...

**Comment by thebigsmileXD** [comment]
If so, than its an PocketMine isue, not imagicalMine

**Comment by aodzip** [comment]
how to reproduce this?

**Comment by PocketKiller** [comment]
Give us more info.

**Comment by Zen4** [comment]
I'm using a MacBook Air to host it on my local wifi. The issue only happens sometimes and vip slots does not solve the problem

**Comment by thebigsmileXD** [comment]
![image](https://cloud.githubusercontent.com/assets/8733998/11761680/c8d296d4-a0cb-11e5-972f-663714f3d972.jpg)
Makes sense.

**Comment by robske110** [comment]
He doent use it for gaming and that was not helpful ;)

**Comment by thebigsmileXD** [comment]
But its still a MAC problem. They BLOCK all forwarding of third party software.

**Comment by robske110** [comment]
What? This issue is DEFENITLY not a mac problem!
MacOSX is UNIX-based, did you know that?
You can acess MUCH EASIER critical settings sections of the system compared to Windows! Forwarding Block, the funniest thing is, MacOSX does not have a Firewall (It does have it, but it is not enabled by default!)

**Comment by robske110** [comment]
Back to the issue, @Zen4 could you please send a screenshot of your configuartion files?

**Comment by robske110** [comment]
So you used localhost:Port ?

**Comment by thebigsmileXD** [comment]
Mac does block it. Really! I had a mac once. 3 month, then i put it on ebay because it was horrible. Video: okay. Sound: okay. Software: well.. Server software: nope.

**Comment by SalmonGER** [comment]
I had this problem on a Linux Debian System too.

**Comment by robske110** [comment]
I am hosting HTTP FTP MINECRAFT PC MINECRAFT PE Servers on my mac and never had Problems!
AND BTW IF YOU HAVE A LITTLE EXPERIENCE YOU CAN RUN WINDOWS ON A MAC WITHOUT PROBLEMS!

**Comment by thebigsmileXD** [comment]
Hackintosh is best. And yea, you can rum Windows on a mac.. But why buying a mac to run windows, if you can use macos? :p

Well, i have an iphone and love it (with jailbreak.. Without its too slow.. Because animations and so on)

I'll set up a macos (looks like nachos) when i am at work again. Thats in january. Then i'll test

**Comment by robske110** [comment]
Hackintosh is the cheapiest way and probaly the best, I done it serveral Times for friends, and in the end i ended up changing random things in the bios, and WAM MacOSX ran on the pc... But we noticed that windows doesn't run anymore, so i slowly raged out and after more random changes both OSes run like a cat wich is just chasing a mouse. Nevermind... And yeah you buy a Mac because of MACOSX, there is no other explanation why you would buy a flatscreen with a computer inside. #Back to the issue!
PROVIDE MORE DETAILS @Zen4

**Comment by keithkfng** [comment]
Please don't go off-topic LOL

**Comment by robske110** [comment]
My last sentence was related to the issue!

**Comment by AndreyNazarchuk** [comment]
@robske110 "i slowly raged out" ROFLMAS :+1:

**Comment by Zen4** [comment]
Details like what. Do you need my ip?

**Comment by Zen4** [comment]
I use dynu ddns but i think its not the problem and yes i use localhost : port

**Comment by Zen4** [comment]
this is my server.properties config file
![screen shot 2015-12-13 at 9 14 20 pm](https://cloud.githubusercontent.com/assets/15248687/11767145/b3963f50-a1de-11e5-89ca-b3796de64377.png)
no seeing rcon password pls xD

**Comment by PocketKiller** [comment]
don't use ModPE Scripting to join..

**Comment by thebigsmileXD** [comment]
Oh.. Uhm, try the ip instead of localhost.
I also couldnt get my server via localhost, just ip

**Comment by Zen4** [comment]
@Pocketkiller what do you mean?

@thebigsmileXD u mean try external ip? I can only connect via internal cos i only have 1 router

**Comment by thebigsmileXD** [comment]
No, i mean use the ip of your host

**Comment by Zen4** [comment]
I host using my own wifi...

**Comment by keithkfng** [comment]
OMG you don't understand, do you? He means using the internal IP of your host.

**Comment by thebigsmileXD** [comment]
THE IP OF THE COMPUTER THE POCKETMINE IS RUNNING ON

**Comment by robske110** [comment]
Easy Explanation for &noobs&
1. Open Browser
2. Type in the adress field NOT GOOGLE 192.168.178.1 or http://fritz.box <-Only with fritzbox
3. Search for Networks Tab
4. Search your computer
5. get the IPAdress
6. PASTE IT IN MINECRAFT

**Comment by thebigsmileXD** [comment]
For that noob that just wrote that:
Don't do that.
Windows:
Open cmd (windows+r, type cmd)
Type ipconfig
Linux&apple:
Open terminal (if not in console)
Type ifconfig

**Comment by robske110** [comment]
Oops, forgot about that easier function...
Why calling MACosx apple?

**Comment by Zen4** [comment]
Oh you mean internal-ip? That is what i use to connect all this while its 192.168.1.100

**Comment by thebigsmileXD** [comment]
Because ios is also apple?

**Comment by Zen4** [comment]
But players from outside use external to connect

**Comment by thebigsmileXD** [comment]
Then use it in the config -.-"

**Comment by thebigsmileXD** [comment]
Seems like you'll never understand..
