### ISSUE TITLE
When FastTransfer Domes back ?

### ISSUE THREAD

**Issue by Underpippo** [ImagicalCorp/ImagicalMine#517]
My Question is, when FastTransfer will implement ?

**Comment by matcracker** [comment]
Depend on client

**Comment by Underpippo** [comment]
I dont geht it ?

**Comment by robske110** [comment]
It probaly wont come back
Mojang removed it

**Comment by Underpippo** [comment]
Okey
But how can i transfer player from one server to another at Moment ?

**Comment by PocketKiller** [comment]
No way.
but using a proxy yes

**Comment by Underpippo** [comment]
And how can i do that ?

**Comment by thebigsmileXD** [comment]
Using BouncyBall or other software.. or just proxies.. i don't really know how to.

**Comment by Underpippo** [comment]
Is anyone here that can help us ?

**Comment by robske110** [comment]
@PeMapModder is currently working on an easyToUse proxy software!
And @thebigsmileXD no, you cannot ^just use an proxy^ because:
The first server will suddenly not recieve any packets, but thats no problem it will close the connection due to timeout.
The secound server will wait for LoginPackets but suddenly becomes some AlreadyInGamePackets like movement. I don't think the client will crash, but maybe the secound server will crash and you will definetly get an timeout on your client due to the secound server doesn't respond. It can if course be worser and the client will crash due to the secound server sends something wich doesn't make sense, but i won't except the secound server to send anything. RakLibBlock maybe...
So you need to make an plugin for the secound server, wich gets an signal there is an player being transferd to you and its name is <name> then the secound server just responds to the client with chunk packets so the client will think oh, there are chunks update and its like an world transfer...
Don't ask me to do that and excuse me if i said anything wrong...

**Comment by robske110** [comment]
Wow such a long post

**Comment by Underpippo** [comment]
Nice answer thanks :D
